### PR TITLE
fix: error in spelling

### PR DESCRIPTION
**Pull request by Justgoncaa**
Fixed spelling mistake in the entrypoint file

### CODE REVIEW

**Comment by Justgoncaa** [comment]
Never mind

**Comment by Justgoncaa** [comment]
Probably Not needed

**Review by umutphp — APPROVED** [review]

**Comment by umutphp** [comment]
Many thanks for the fix. Sorry to respond late. It was a busy weekend :)

**Comment by Justgoncaa** [comment]
It’s okay, I happy to help at anytime

**Comment by Justgoncaa** [comment]
I don’t mind waiting.

**Pull request merged**
